# Generated by Django 4.1.3 on 2022-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_semester_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.assessment_type'),
            preserve_default=False,
        ),
    ]
