# Generated by Django 4.1.3 on 2022-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0005_assessment_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='obtained_marks',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
