# Generated by Django 4.1.3 on 2022-12-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_assessment_obtained_marks_alter_assessment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(),
        ),
    ]
