# Generated by Django 4.1.3 on 2022-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_study_group_participant_group_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='study_group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
