# Generated by Django 4.1.3 on 2022-12-23 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_group_message_id_alter_participant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_message',
            name='is_read',
        ),
        migrations.CreateModel(
            name='Read_Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group_message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read Report',
                'verbose_name_plural': 'Read Reports',
                'db_table': 'chat_read_reports',
                'ordering': ('-date',),
            },
        ),
    ]
