# Generated by Django 4.1.4 on 2022-12-23 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_study_group_course_code_study_group_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ditch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ditched', models.BooleanField()),
                ('u1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1', to=settings.AUTH_USER_MODEL)),
                ('u2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
