# Generated by Django 4.1.3 on 2022-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_ditch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
