# Generated by Django 4.1.3 on 2022-12-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_profile_picture'),
        ('chat', '0008_group_message_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_message',
            name='university',
        ),
        migrations.AddField(
            model_name='study_group',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
            preserve_default=False,
        ),
    ]
