# Generated by Django 4.1.3 on 2022-12-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=300)),
                ('email_pattern', models.CharField(max_length=100)),
                ('sid_pattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passwords', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('periods', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.university')),
            ],
        ),
    ]
