# Generated by Django 4.1.3 on 2022-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
                ('contributor', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
