# Generated by Django 4.1.3 on 2022-12-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_s_id_user_student_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register_date',
            new_name='start_date',
        ),
    ]
