# Generated by Django 4.1.3 on 2022-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_department_remove_user_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwords',
        ),
    ]
