# Generated by Django 4.1.3 on 2022-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_content_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_request',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
