# Generated by Django 4.1.3 on 2022-12-15 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwords',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
