# Generated by Django 4.1.3 on 2022-12-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_register_date_user_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='user_name',
        ),
    ]
