# Generated by Django 4.1.3 on 2022-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
                ('contributor', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
