# Generated by Django 4.1.3 on 2022-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_pictures/avatar-male.png', upload_to='uploads/profile_pictures/'),
        ),
    ]
