# Generated by Django 4.1.3 on 2022-12-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_content_content_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_request',
            name='contributor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='content_request',
            name='requester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
